### ISSUE TITLE
[BUG] 채팅 버그

### ISSUE THREAD

**Issue by bytecakelake** [gunyu1019/chzzk_py#14]
## Describe the bug<br/>

주기적으로 의도된 출력대신 에러를 출력합니다.

## To Reproduce<br/>

venv python3.11.7 가상환경을 생성하여 실행합니다.

#### livechatlogger.py (python 3.7^)
```python3
from chzzkpy.chat import ChatClient, ChatMessage
import json

client = ChatClient("체널id")

## ** 필수 - cookies.json **
auth = json.load(open("cookies.json", "rb")) 

@client.event
async def on_chat(message: ChatMessage):
    print(f"[{message.time.strftime('%H:%M:%S')}][{message.profile.nickname}]:{message.content}")

client.run(**auth)
```

## Expected behavior<br/>

정상적으로 채팅을 출력합니다.
```log
...
[13:56:31][나몬이]:대리로 낼 수 도 있지
[13:56:31][밀다Milda]:있긴 해
[13:56:32][너야2]:다 적어서 내
[13:56:34][(nickname)]:(message)
[13:56:34][슬러쉬물음표]:근데 저거 어디로 제출 받음?
[13:56:35][달콤한소곰]:실명이랑 생년월일을 수집해?
[13:56:36][달을삼킨커비]:혹시 모르니까
...
```

## Actual Results<br/>

프로그램이 멈추지 않고, 
원래 메세지 대신 에러메세지를 주기적으로 내뱉습니다.
```log
...
[13:56:31][나몬이]:대리로 낼 수 도 있지
[13:56:31][밀다Milda]:있긴 해
[13:56:32][너야2]:다 적어서 내
1 validation error for ChatMessage
extras.emojis
  Field required [type=missing, input_value={'chatType': 'STREAMING',...9f/0NBsnGXPu1//PGQCw=='}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\LCL\.venv\Lib\site-packages\chzzkpy\chat\state.py", line 71, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\LCL\.venv\Lib\site-packages\chzzkpy\chat\state.py", line 120, in parse_chat
    self._parse_all_type_of_chat(data)
  File "C:\Users\Admin\Desktop\LCL.venv\Lib\site-packages\chzzkpy\chat\state.py", line 112, in _parse_all_type_of_chat
    validated_data = ChatMessage.model_validate_with_client(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\LCL\.venv\Lib\site-packages\chzzkpy\chat\message.py", line 100, in model_validate_with_client
    model = super().model_validate(obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\LCL\.venv\Lib\site-packages\pydantic\main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatMessage
extras.emojis
  Field required [type=missing, input_value={'chatType': 'STREAMING',...9f/0NBsnGXPu1//PGQCw=='}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
[13:56:34][슬러쉬물음표]:근데 저거 어디로 제출 받음?
[13:56:35][달콤한소곰]:실명이랑 생년월일을 수집해?
[13:56:36][달을삼킨커비]:혹시 모르니까
...
```

## Device Info<br/>

os: windos 11 pro

## Additional context<br/>

아마도 on_chat 함수를 호출하기전의 로직이 문제인듯합니다.

**Comment by gunyu1019** [comment]
위 예외를 참고하여 조치는 완료되었습니다.  하지만 예외 상황을 정확하게 파악된 것이 아니기 때문에 오류가 발생한다면 re-open를 부탁드립니다.
