### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'chat_channel_id' 자꾸 이런 오류가 뜨네요

### ISSUE THREAD

**Issue by DOCYEDOC** [gunyu1019/chzzk_py#17]
Traceback (most recent call last):
  File "f:\Ahko\chzzk.py", line 149, in <module>
    chzzk.run("NID_AUT", "NID_SES")
  File "F:\Ahko\.venv\lib\site-packages\chzzkpy\chat\chat_client.py", line 99, in run
    self.loop.run_until_complete(wrapper)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "F:\Ahko\.venv\lib\site-packages\chzzkpy\chat\chat_client.py", line 107, in start
    await self.connect()
  File "F:\Ahko\.venv\lib\site-packages\chzzkpy\chat\chat_client.py", line 114, in connect
    self.chat_channel_id = status.chat_channel_id
AttributeError: 'NoneType' object has no attribute 'chat_channel_id'

이런 오류가 뜨면서 갑자기 먹통이 되버렸습니다

**Comment by gunyu1019** [comment]
원인 조사를 해보고 빠른 시일 내에 패치해드리도록 하겠습니다.

**Comment by gunyu1019** [comment]
해당 Traceback은 채널에 채팅 ID값이 조회되지 않아 발생하는 예외로 확인됩니다. 
* 봇을 돌리려는 채널의 방송이 최근에 있어는지 확인해 주실 수 있을까요?
위 사항이 아니라면 자세한 예외 구현을 위해 comment 남겨주시면 감사하겠습니다.

빠른 시일 내에 Exception을 추가하여 다른 개발자도 인지할 수 있도록 패치하겠습니다.

**Comment by gunyu1019** [comment]
#19 에서 조치가 완료되었으므로, close 처리하겠습니다. 제보해 주셔서 감사합니다.
